# Generated by Django 4.2.17 on 2025-01-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentImage',
            new_name='PDFImage',
        ),
    ]
