# Generated by Django 4.2.17 on 2025-01-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0002_rename_studentimage_pdfimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
